package com.rhythmatician.lodiffusion.voxy;

import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.function.Consumer;

import net.minecraft.client.Minecraft;
import net.minecraft.world.level.chunk.LevelChunk;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Exposes Voxy's chunk processing pipeline as a programmatic API.
 *
 * <p>Allows the dataset generation system to request on-demand chunk processing without requiring
 * a player to be nearby. Instead of relying on chunk load events, this API provides:
 * <ul>
 *   <li>{@link #processChunk(int, int)} - Process a chunk at specific coordinates</li>
 *   <li>{@link #registerSectionCaptureListener(Consumer)} - Hook into VoxelizedSection data before
 *       insertion into Voxy's cache</li>
 * </ul>
 *
 * <p><b>Usage Pattern:</b>
 * <pre>
 * // Register callback
 * VoxyProcessingAPI.registerSectionCaptureListener(section -> {
 *     exportSectionToDataset(section);
 * });
 *
 * // Request chunk processing
 * VoxyProcessingAPI.processChunk(100, 200);
 * </pre>
 *
 * <p><b>Design Notes:</b>
 * <ul>
 *   <li>This is a client-side API; chunks must be loaded on the client (e.g., via Chunky)</li>
 *   <li>The section capture callback is invoked <b>after mipping</b> but <b>before Voxy's storage</b>
 *       to obtain raw voxelized data</li>
 *   <li>Processing is asynchronous; Voxy's ingest service handles the actual work on its worker
 *       thread</li>
 * </ul>
 */
public final class VoxyProcessingAPI {
    private static final Logger LOGGER = LoggerFactory.getLogger(VoxyProcessingAPI.class);

    /**
     * Listeners for VoxelizedSection data capture. These are called with the VoxelizedSection
     * object after mipping but before insertion into Voxy's world engine.
     *
     * <p>The listener receives a {@code VoxelizedSectionSnapshot} which is a copy/snapshot of the
     * data suitable for export.
     */
    private static final ConcurrentLinkedDeque<Consumer<VoxelizedSectionSnapshot>> SECTION_LISTENERS = new ConcurrentLinkedDeque<>();

    private VoxyProcessingAPI() {}

    /**
     * Register a listener to receive VoxelizedSection data after mipping.
     *
     * <p>The snapshot is captured at the point where Voxy has completed mipping (LOD level
     * generation) but before the section is inserted into the world engine. This ensures you
     * capture the complete multi-level LOD data in its pre-compressed form.
     *
     * @param listener Consumer that receives VoxelizedSectionSnapshot objects
     */
    public static void registerSectionCaptureListener(
            Consumer<VoxelizedSectionSnapshot> listener) {
        SECTION_LISTENERS.add(listener);
        LOGGER.debug("Registered section capture listener. Total listeners: {}", SECTION_LISTENERS.size());
    }

    /**
     * Unregister a previously registered listener.
     *
     * @param listener The listener to remove
     */
    public static void unregisterSectionCaptureListener(
            Consumer<VoxelizedSectionSnapshot> listener) {
        SECTION_LISTENERS.remove(listener);
        LOGGER.debug("Unregistered section capture listener. Remaining listeners: {}", SECTION_LISTENERS.size());
    }

    /**
     * Clear all registered listeners.
     */
    public static void clearSectionCaptureListeners() {
        SECTION_LISTENERS.clear();
    }

    /**
     * Get the count of active listeners.
     *
     * @return Number of registered listeners
     */
    public static int getListenerCount() {
        return SECTION_LISTENERS.size();
    }

    /**
     * Fire section capture callbacks. Called internally by the mixin after mipping.
     *
     * @param snapshot The VoxelizedSectionSnapshot to pass to listeners
     */
    static void fireCaptureSectionCallbacks(VoxelizedSectionSnapshot snapshot) {
        for (Consumer<VoxelizedSectionSnapshot> listener : SECTION_LISTENERS) {
            try {
                listener.accept(snapshot);
            } catch (Exception e) {
                LOGGER.warn("Exception in section capture listener", e);
            }
        }
    }

    /**
     * Process a chunk at the given coordinates on-demand, without requiring a player nearby.
     *
     * <p>The chunk must already be loaded on the client (e.g., pre-generated by Chunky). This
     * method:
     * <ol>
     *   <li>Retrieves the LevelChunk from the client chunk cache</li>
     *   <li>Enqueues it with Voxy's VoxelIngestService for processing</li>
     *   <li>Returns immediately (processing is asynchronous)</li>
     * </ol>
     *
     * @param chunkX The chunk X coordinate
     * @param chunkZ The chunk Z coordinate
     * @return true if the chunk was successfully enqueued, false if the chunk is not loaded or
     *         Voxy is unavailable
     */
    public static boolean processChunk(int chunkX, int chunkZ) {
        if (!VoxyDetection.isAvailable()) {
            LOGGER.warn("Voxy is not available; cannot process chunk ({}, {})", chunkX, chunkZ);
            return false;
        }

        Minecraft mc = Minecraft.getInstance();
        if (mc.level == null) {
            LOGGER.warn("No world loaded; cannot process chunk ({}, {})", chunkX, chunkZ);
            return false;
        }

        // Get the chunk from the client cache
        LevelChunk chunk = mc.level.getChunk(chunkX, chunkZ);
        if (chunk == null) {
            LOGGER.debug("Chunk ({}, {}) not loaded in client cache", chunkX, chunkZ);
            return false;
        }

        // Try to ingest the chunk using Voxy's static API
        return tryIngestChunkViaReflection(chunk);
    }

    /**
     * Attempt to ingest a chunk via Voxy's public API using reflection.
     *
     * <p>Uses {@code VoxelIngestService.tryAutoIngestChunk(LevelChunk)} to properly route the
     * chunk to the correct world engine based on the chunk's level.
     *
     * @param chunk The chunk to ingest
     * @return true if ingestion was successful or enqueued, false otherwise
     */
    private static boolean tryIngestChunkViaReflection(LevelChunk chunk) {
        try {
            // Load the VoxelIngestService class via reflection
            Class<?> voxelIngestServiceClass =
                    Class.forName("me.cortex.voxy.common.world.service.VoxelIngestService");
            java.lang.reflect.Method tryAutoIngestMethod =
                    voxelIngestServiceClass.getMethod("tryAutoIngestChunk", LevelChunk.class);

            // Call VoxelIngestService.tryAutoIngestChunk(chunk)
            Boolean result = (Boolean) tryAutoIngestMethod.invoke(null, chunk);
            if (Boolean.TRUE.equals(result)) {
                LOGGER.debug("Chunk ({}, {}) enqueued for processing", chunk.getPos().x, chunk.getPos().z);
            } else {
                LOGGER.debug("Chunk ({}, {}) was not enqueued (possibly invalid or no valid world)",
                        chunk.getPos().x, chunk.getPos().z);
            }
            return result;
        } catch (ClassNotFoundException e) {
            LOGGER.warn("VoxelIngestService class not found; Voxy may not be installed", e);
            return false;
        } catch (NoSuchMethodException e) {
            LOGGER.warn("VoxelIngestService.tryAutoIngestChunk method not found", e);
            return false;
        } catch (Exception e) {
            LOGGER.warn("Error invoking VoxelIngestService.tryAutoIngestChunk", e);
            return false;
        }
    }
}
